app = "ai-visibility-jobs"
primary_region = "iad"

[build]
  dockerfile = "./Dockerfile"

[processes]
  worker = "node dist/index.js"

[checks]
  [checks.alive]
    type = "tcp"
    port = 8081
    interval = "15s"
    timeout = "2s"
